on: [push]

name: Build and test

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Dependencies
#        https://github.com/ggez/ggez/issues/100
#        https://stackoverflow.com/questions/73693257/how-to-fix-could-not-find-system-library-libudev-when-installing-cargo-flash
        run: sudo apt-get install -y libasound2-dev libudev-dev
      - uses: actions-rs/cargo@v1
        with:
         command: test
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features