on: [pull_request, push]

name: Build and test

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Dependencies
        run: sudo apt-get install -y libasound2-dev
      - uses: actions-rs/cargo@v1
        with:
         command: test
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features